apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k0rzak5ue-python 
  janus-idp.io/tekton: k0rzak5ue-python
  backstage.io/kubernetes-id: k0rzak5ue-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k0rzak5ue-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  